In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# NMI flights

In [6]:
df_nmi = pd.read_csv("csv_data/google_flight_nmi.csv")
df_nmi = df_nmi.drop(columns=['Unnamed: 0'])
df_nmi.head()

,Departure_Time,Arrival_Time,Airline,Duration,Route,Stops,Layover_Time_Location,CO2_Emissions,Emissions_Change,Price,Class
0,8:00 AM,2:50 PM,IndiGo,6 hr 50 min,NMI–BLR,1 stop,3 hr 50 min KLH,88 kg CO2e,+28% emissions,"₹6,073",economy
1,11:05 AM,8:55 PM,IndiGo,9 hr 50 min,NMI–BLR,1 stop,6 hr 50 min GOI,92 kg CO2e,+33% emissions,"₹6,937",economy
2,11:05 AM,3:45 PM,IndiGo,4 hr 40 min,NMI–BLR,1 stop,1 hr 50 min GOI,92 kg CO2e,+33% emissions,"₹8,086",economy
3,7:15 PM,11:00 PM,IndiGo,3 hr 45 min,BLR–NMI,1 stop,1 hr 20 min GOI,91 kg CO2e,+32% emissions,"₹6,005",economy
4,5:40 PM,11:00 PM,IndiGo,5 hr 20 min,BLR–NMI,1 stop,2 hr 50 min GOI,91 kg CO2e,+32% emissions,"₹6,005",economy

#### Data preprocessing for EDA:

In [ ]:
# convert price to numeric, and remove symbols:
df_nmi["Price"] = (
    df_nmi["Price"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
)
df_nmi["Price"] = pd.to_numeric(df_nmi["Price"])

# convert "Route" into 2 columns- Source and Destination
df_nmi[["Source", "Destination"]] = df_nmi["Route"].str.split("–", expand=True)

# convert Duration into decimal
df_nmi[["hr", "min"]] = df_nmi["Duration"].str.extract(r"(\d+)\s*hr\s*(\d+)\s*min").astype(int)
df_nmi["Duration"] = df_nmi["hr"]+df_nmi["min"] / 60
df_nmi.drop(columns=["hr", "min"], inplace=True)

# just get the number from CO2_Emissions and Emissions_Change
df_nmi["CO2_Emissions"] = (
    df_nmi["CO2_Emissions"].str.extract(r"(\d+)").astype(int)
)
df_nmi["Emissions_Change"] = (
    df_nmi["Emissions_Change"]
    .str.extract(r"([+-]?\d+)")
    .astype(int)
)

# remove unwanted columns
df_nmi=df_nmi.drop(["Route"], axis=1)

### Data:

In [4]:
df_nmi.head()

,Departure_Time,Arrival_Time,Airline,Duration,Route,Stops,Layover_Time_Location,CO2_Emissions,Emissions_Change,Price,Class,Source,Destination
0,8:00 AM,2:50 PM,IndiGo,6 hr 50 min,NMI–BLR,1 stop,3 hr 50 min KLH,88 kg CO2e,+28% emissions,6073,economy,NMI,BLR
1,11:05 AM,8:55 PM,IndiGo,9 hr 50 min,NMI–BLR,1 stop,6 hr 50 min GOI,92 kg CO2e,+33% emissions,6937,economy,NMI,BLR
2,11:05 AM,3:45 PM,IndiGo,4 hr 40 min,NMI–BLR,1 stop,1 hr 50 min GOI,92 kg CO2e,+33% emissions,8086,economy,NMI,BLR
3,7:15 PM,11:00 PM,IndiGo,3 hr 45 min,BLR–NMI,1 stop,1 hr 20 min GOI,91 kg CO2e,+32% emissions,6005,economy,BLR,NMI
4,5:40 PM,11:00 PM,IndiGo,5 hr 20 min,BLR–NMI,1 stop,2 hr 50 min GOI,91 kg CO2e,+32% emissions,6005,economy,BLR,NMI

#### Number of flights:

In [32]:
len(df_nmi)

98

#### Average price:

In [ ]:
print(df_nmi["Price"].mean())

7193.877551020408

#### Number of flights to (and fro) each destination:

In [34]:
# Flights from NMI 
from_nmi = (
    df_nmi[df_nmi["Source"] == "NMI"]
    .groupby("Destination")
    .size()
    .rename("Flights from NMI")
)

# Flights to NMI 
to_nmi = (
    df_nmi[df_nmi["Destination"] == "NMI"]
    .groupby("Source")
    .size()
    .rename("Flights to NMI")
)

# Combine 
flights_nmi = pd.concat([to_nmi, from_nmi], axis=1).fillna(0).astype(int)

flights_nmi.index.name = "Airport"
flights_nmi = flights_nmi.reset_index()

print(flights_nmi)

   Airport  Flights to NMI  Flights from NMI
0      BLR               7                 5
1      CCU               3                 3
2      CJB               3                 5
3      COK               4                 4
4      DEL               6                 7
5      GOI               2                 2
6      GOX               2                 1
7      HYD               2                 2
8      IXC               6                 2
9      IXE               3                 3
10     JAI               2                 2
11     MAA               5                 4
12     PAT               4                 3
13     TRV               3                 2
14     IXR               0                 1

# BOM flights

In [ ]:
df_bom = pd.read_csv("csv_data/google_flight_bom.csv")
df_bom = df_bom.drop(columns=['Unnamed: 0'])
df_bom.head()

,Departure_Time,Arrival_Time,Airline,Duration,Route,Stops,Layover_Time_Location,CO2_Emissions,Emissions_Change,Price,Class
0,11:20 AM,3:45 PM,IndiGo,4 hr 25 min,BOM–BLR,1 stop,1 hr 55 min GOI,92 kg CO2e,+33% emissions,"₹4,383",economy
1,4:40 PM,10:15 PM,IndiGo,5 hr 35 min,BOM–BLR,1 stop,2 hr 50 min GOI,104 kg CO2e,+51% emissions,"₹4,383",economy
2,5:45 AM,10:55 AM,IndiGo,5 hr 10 min,BOM–BLR,1 stop,2 hr 15 min HYD,106 kg CO2e,+54% emissions,"₹4,514",economy
3,9:15 AM,1:35 PM,IndiGo,4 hr 20 min,BOM–BLR,1 stop,1 hr 45 min GOX,95 kg CO2e,+38% emissions,"₹4,514",economy
4,3:15 PM,7:05 PM,IndiGo,3 hr 50 min,BOM–BLR,1 stop,1 hr HYD,106 kg CO2e,+54% emissions,"₹4,514",economy

#### Data preprocessing for EDA-

In [6]:
# convert price to numeric, and remove symbols:
df_bom["Price"] = (
    df_bom["Price"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
)
df_bom["Price"] = pd.to_numeric(df_bom["Price"])

# convert "Route" into 2 columns- Source and Destination
df_bom[["Source", "Destination"]] = df_bom["Route"].str.split("–", expand=True)

In [ ]:
df_bom.head()

,Departure_Time,Arrival_Time,Airline,Duration,Route,Stops,Layover_Time_Location,CO2_Emissions,Emissions_Change,Price,Class,Source,Destination
0,11:20 AM,3:45 PM,IndiGo,4 hr 25 min,BOM–BLR,1 stop,1 hr 55 min GOI,92 kg CO2e,+33% emissions,4383,economy,BOM,BLR
1,4:40 PM,10:15 PM,IndiGo,5 hr 35 min,BOM–BLR,1 stop,2 hr 50 min GOI,104 kg CO2e,+51% emissions,4383,economy,BOM,BLR
2,5:45 AM,10:55 AM,IndiGo,5 hr 10 min,BOM–BLR,1 stop,2 hr 15 min HYD,106 kg CO2e,+54% emissions,4514,economy,BOM,BLR
3,9:15 AM,1:35 PM,IndiGo,4 hr 20 min,BOM–BLR,1 stop,1 hr 45 min GOX,95 kg CO2e,+38% emissions,4514,economy,BOM,BLR
4,3:15 PM,7:05 PM,IndiGo,3 hr 50 min,BOM–BLR,1 stop,1 hr HYD,106 kg CO2e,+54% emissions,4514,economy,BOM,BLR
5,6:50 PM,10:50 PM,IndiGo,4 hr,BLR–BOM,1 stop,1 hr 10 min IXE,110 kg CO2e,+59% emissions,5906,economy,BLR,BOM
6,4:40 PM,9:20 PM,IndiGo,4 hr 40 min,BOM–MAA,1 stop,1 hr 40 min GOI,119 kg CO2e,+47% emissions,5485,economy,BOM,MAA
7,3:15 PM,7:10 PM,IndiGo,3 hr 55 min,BOM–MAA,1 stop,1 hr 10 min HYD,109 kg CO2e,+35% emissions,5616,economy,BOM,MAA
8,3:45 PM,9:00 PM,IndiGo,5 hr 15 min,BOM–MAA,1 stop,2 hr 15 min CJB,119 kg CO2e,+47% emissions,5695,economy,BOM,MAA
9,6:35 PM,11:10 PM,IndiGo,4 hr 35 min,BOM–MAA,1 stop,1 hr 10 min IDR,149 kg CO2e,+84% emissions,5826,economy,BOM,MAA
10,10:55 AM,2:50 PM,IndiGo,3 hr 55 min,MAA–BOM,1 stop,1 hr BLR,106 kg CO2e,+33% emissions,5522,economy,MAA,BOM
11,8:55 AM,1:20 PM,IndiGo,4 hr 25 min,MAA–BOM,1 stop,1 hr 25 min BLR,106 kg CO2e,+33% emissions,5522,economy,MAA,BOM
12,2:35 PM,7:05 PM,IndiGo,4 hr 30 min,MAA–BOM,1 stop,1 hr 35 min BLR,108 kg CO2e,+35% emissions,5522,economy,MAA,BOM
13,8:00 AM,12:50 PM,IndiGo,4 hr 50 min,MAA–BOM,1 stop,1 hr 35 min COK,134 kg CO2e,+68% emissions,5864,economy,MAA,BOM
14,5:45 AM,10:25 AM,IndiGo,4 hr 40 min,BOM–DEL,1 stop,1 hr 50 min BDQ,112 kg CO2e,+10% emissions,6339,economy,BOM,DEL
15,1:30 AM,6:45 AM,IndiGo,5 hr 15 min,BOM–DEL,1 stop,2 hr 10 min AMD,120 kg CO2e,+18% emissions,6339,economy,BOM,DEL
16,6:10 AM,11:35 AM,IndiGo,5 hr 25 min,BOM–DEL,1 stop,2 hr 25 min AMD,123 kg CO2e,+21% emissions,6339,economy,BOM,DEL
17,2:40 PM,7:40 PM,IndiGo,5 hr,BOM–DEL,1 stop,2 hr HSR,126 kg CO2e,+24% emissions,6339,economy,BOM,DEL
18,6:40 PM,11:30 PM,IndiGo,4 hr 50 min,BOM–DEL,1 stop,1 hr 50 min AMD,111 kg CO2e,+9% emissions,6339,economy,BOM,DEL
19,5:35 PM,9:20 PM,IndiGo,3 hr 45 min,BOM–DEL,1 stop,1 hr UDR,126 kg CO2e,+24% emissions,6470,economy,BOM,DEL
20,12:15 AM,5:30 AM,IndiGo,5 hr 15 min,DEL–BOM,1 stop,2 hr 10 min AMD,115 kg CO2e,+12% emissions,5928,economy,DEL,BOM
21,9:50 PM,2:55 AM+1,IndiGo,5 hr 5 min,DEL–BOM,1 stop,1 hr 50 min AMD,115 kg CO2e,+12% emissions,5928,economy,DEL,BOM
22,5:10 AM,9:35 AM,IndiGo,4 hr 25 min,DEL–BOM,1 stop,1 hr 30 min AMD,124 kg CO2e,+20% emissions,6228,economy,DEL,BOM
23,7:30 AM,12:20 PM,IndiGo,4 hr 50 min,DEL–BOM,1 stop,1 hr 50 min AMD,115 kg CO2e,+12% emissions,6228,economy,DEL,BOM
24,7:30 PM,12:30 AM+1,IndiGo,5 hr,DEL–BOM,1 stop,2 hr 10 min AMD,115 kg CO2e,+12% emissions,6237,economy,DEL,BOM
25,1:10 AM,8:15 AM,IndiGo,7 hr 5 min,BOM–IXE,1 stop,4 hr 10 min BLR,107 kg CO2e,+70% emissions,5952,economy,BOM,IXE
26,3:35 PM,7:45 PM,IndiGo,4 hr 10 min,BOM–IXE,1 stop,1 hr 25 min BLR,111 kg CO2e,+76% emissions,5952,economy,BOM,IXE
27,10:20 PM,8:15 AM+1,IndiGo,9 hr 55 min,BOM–IXE,1 stop,6 hr 55 min BLR,107 kg CO2e,+70% emissions,5952,economy,BOM,IXE
28,8:05 AM,6:00 PM,IndiGo,9 hr 55 min,BOM–IXE,1 stop,7 hr 5 min BLR,109 kg CO2e,+73% emissions,6854,economy,BOM,IXE
29,8:05 AM,3:35 PM,IndiGo,7 hr 30 min,BOM–IXE,1 stop,4 hr 40 min BLR,109 kg CO2e,+73% emissions,6878,economy,BOM,IXE
30,8:45 AM,1:20 PM,IndiGo,4 hr 35 min,IXE–BOM,1 stop,1 hr 40 min BLR,108 kg CO2e,+64% emissions,6062,economy,IXE,BOM
31,11:30 AM,7:05 PM,IndiGo,7 hr 35 min,IXE–BOM,1 stop,4 hr 40 min BLR,113 kg CO2e,+71% emissions,6062,economy,IXE,BOM
32,9:10 PM,4:30 AM+1,IndiGo,7 hr 20 min,IXE–BOM,1 stop,3 hr 50 min HYD,132 kg CO2e,+100% emissions,7049,economy,IXE,BOM
33,6:15 AM,12:00 PM,IndiGo,5 hr 45 min,BOM–HYD,1 stop,2 hr 35 min UDR,129 kg CO2e,+122% emissions,4766,economy,BOM,HYD
34,7:15 AM,12:30 PM,IndiGo,5 hr 15 min,BOM–HYD,1 stop,2 hr 10 min RPR,127 kg CO2e,+119% emissions,4766,economy,BOM,HYD
35,4:30 AM,9:30 AM,IndiGo,5 hr,BOM–HYD,1 stop,1 hr 50 min BLR,122 kg CO2e,+110% emissions,4976,economy,BOM,HYD
36,6:10 AM,10:15 AM,IndiGo,4 hr 5 min,BOM–HYD,1 stop,1 hr 5 min AMD,138 kg CO2e,+138% emissions,4976,economy,BOM,HYD
37,9:15 AM,3:05 PM,IndiGo,5 hr 50 min,BOM–HYD,1 stop,3 hr 10 min GOX,96 kg CO2e,+66% emissions,4976,economy,BOM,HYD
38,3:10 AM,9:20 AM,SriLankan,6 hr 10 min,BOM–HYD,1 stop,1 hr 45 min CMB,268 kg CO2e,+362% emissions,22953,economy,BOM,HYD
39,2:30 PM,7:05 PM,IndiGo,4 hr 35 min,HYD–BOM,1 stop,1 hr 25 min BLR,118 kg CO2e,+100% emissions,5018,economy,HYD,BOM
40,8:05 AM,1:20 PM,IndiGo,5 hr 15 min,HYD–BOM,1 stop,2 hr BLR,118 kg CO2e,+100% emissions,5018,economy,HYD,BOM
41,9:35 AM,2:50 PM,IndiGo,5 hr 15 min,HYD–BOM,1 stop,2 hr 5 min BLR,118 kg CO2e,+100% emissions,5018,economy,HYD,BOM
42,11:20 AM,5:50 PM,IndiGo,6 hr 30 min,HYD–BOM,1 stop,3 hr 55 min GOI,99 kg CO2e,+68% emissions,5018,economy,HYD,BOM
43,6:15 PM,11:00 PM,IndiGo,4 hr 45 min,HYD–BOM,1 stop,1 hr 20 min AMD,121 kg CO2e,+105% emissions,5018,economy,HYD,BOM
44,7:40 PM,1:25 AM+1,IndiGo,5 hr 45 min,HYD–BOM,1 stop,3 hr 10 min GOI,103 kg CO2e,+75% emissions,5018,economy,HYD,BOM
45,9:15 PM,2:55 AM+1,IndiGo,5 hr 40 min,HYD–BOM,1 stop,2 hr 15 min AMD,130 kg CO2e,+120% emissions,5018,economy,HYD,BOM
46,2:10 PM,6:40 PM,IndiGo,4 hr 30 min,HYD–BOM,1 stop,1 hr 10 min MAA,136 kg CO2e,+131% emissions,5360,economy,HYD,BOM
47,10:15 AM,7:50 PM,SriLankan,9 hr 35 min,HYD–BOM,1 stop,5 hr 5 min CMB,282 kg CO2e,+378% emissions,26381,economy,HYD,BOM
48,4:30 AM,12:40 PM,Etihad,8 hr 10 min,HYD–BOM,1 stop,1 hr 10 min AUH,366 kg CO2e,+520% emissions,77216,economy,HYD,BOM
49,2:45 AM,8:05 AM,IndiGo,5 hr 20 min,BOM–CCU,1 stop,1 hr 35 min HYD,150 kg CO2e,+28% emissions,6244,economy,BOM,CCU
50,2:25 PM,8:25 PM,IndiGo,6 hr,BOM–CCU,1 stop,2 hr 35 min RPR,145 kg CO2e,+24% emissions,6034,economy,BOM,CCU
51,10:15 AM,4:20 PM,IndiGo,6 hr 5 min,BOM–CCU,1 stop,2 hr 20 min HYD,150 kg CO2e,+28% emissions,6244,economy,BOM,CCU
52,4:50 PM,10:40 PM,IndiGo,5 hr 50 min,BOM–CCU,1 stop,2 hr 15 min IDR,151 kg CO2e,+29% emissions,6244,economy,BOM,CCU
53,6:10 AM,12:00 PM,IndiGo,5 hr 50 min,BOM–CCU,1 stop,1 hr 55 min AMD,171 kg CO2e,+46% emissions,6323,economy,BOM,CCU
54,6:40 PM,12:40 AM+1,IndiGo,6 hr,BOM–CCU,1 stop,2 hr AMD,158 kg CO2e,+35% emissions,6323,economy,BOM,CCU
55,5:00 PM,11:00 PM,IndiGo,6 hr,BOM–CCU,1 stop,1 hr 25 min BLR,180 kg CO2e,+54% emissions,6454,economy,BOM,CCU
56,4:30 AM,10:35 AM,IndiGo,6 hr 5 min,BOM–CCU,1 stop,1 hr 45 min BLR,180 kg CO2e,+54% emissions,6922,economy,BOM,CCU
57,8:40 AM,3:15 PM,IndiGo,6 hr 35 min,BOM–CCU,1 stop,1 hr 55 min DED,206 kg CO2e,+76% emissions,6922,economy,BOM,CCU
58,4:50 PM,9:55 PM,IndiGo,5 hr 5 min,BOM–CCU,1 stop,1 hr BBI,149 kg CO2e,+27% emissions,7093,economy,BOM,CCU
59,6:55 PM,11:45 PM,IndiGo,4 hr 50 min,CCU–BOM,1 stop,1 hr IDR,148 kg CO2e,+28% emissions,7673,economy,CCU,BOM
60,6:00 AM,12:20 PM,IndiGo,6 hr 20 min,CCU–BOM,1 stop,2 hr 15 min AMD,164 kg CO2e,+41% emissions,7752,economy,CCU,BOM
61,8:35 AM,2:45 PM,IndiGo,6 hr 10 min,CCU–BOM,1 stop,1 hr 50 min MAA,180 kg CO2e,+55% emissions,7883,economy,CCU,BOM
62,8:05 AM,2:00 PM,IndiGo,5 hr 55 min,BOM–COK,1 stop,3 hr BLR,110 kg CO2e,+38% emissions,6953,economy,BOM,COK
63,7:05 AM,12:05 PM,IndiGo,5 hr,COK–BOM,1 stop,1 hr 55 min BLR,117 kg CO2e,+39% emissions,6373,economy,COK,BOM
64,9:40 AM,2:50 PM,IndiGo,5 hr 10 min,COK–BOM,1 stop,2 hr 5 min BLR,112 kg CO2e,+33% emissions,6373,economy,COK,BOM
65,12:00 PM,4:05 PM,IndiGo,4 hr 5 min,COK–BOM,1 stop,1 hr 5 min BLR,112 kg CO2e,+33% emissions,6373,economy,COK,BOM
66,7:35 PM,12:05 AM+1,IndiGo,4 hr 30 min,COK–BOM,1 stop,1 hr 30 min BLR,112 kg CO2e,+33% emissions,6373,economy,COK,BOM
67,9:40 PM,2:50 AM+1,IndiGo,5 hr 10 min,COK–BOM,1 stop,2 hr 10 min BLR,112 kg CO2e,+33% emissions,6373,economy,COK,BOM
68,6:10 AM,1:20 PM,IndiGo,7 hr 10 min,BOM–IXC,1 stop,4 hr 10 min AMD,139 kg CO2e,+9% emissions,8071,economy,BOM,IXC
69,8:50 AM,1:20 PM,IndiGo,4 hr 30 min,BOM–IXC,1 stop,1 hr 20 min AMD,131 kg CO2e,Avg emissions,8421,economy,BOM,IXC
70,6:30 AM,11:00 AM,IndiGo,4 hr 30 min,IXC–BOM,1 stop,1 hr 20 min DEL,123 kg CO2e,+18% emissions,7950,economy,IXC,BOM
71,3:30 PM,10:10 PM,IndiGo,6 hr 40 min,IXC–BOM,1 stop,3 hr 30 min DEL,123 kg CO2e,+18% emissions,7950,economy,IXC,BOM
72,4:50 PM,11:00 PM,IndiGo,6 hr 10 min,IXC–BOM,1 stop,2 hr 55 min DEL,123 kg CO2e,+18% emissions,7950,economy,IXC,BOM
73,1:55 PM,6:25 PM,IndiGo,4 hr 30 min,IXC–BOM,1 stop,1 hr 30 min AMD,134 kg CO2e,+29% emissions,9027,economy,IXC,BOM
74,8:05 AM,5:10 PM,IndiGo,9 hr 5 min,BOM–CJB,1 stop,6 hr 15 min BLR,101 kg CO2e,+26% emissions,7349,economy,BOM,CJB
75,5:00 AM,2:55 PM,IndiGo,9 hr 55 min,BOM–CJB,1 stop,6 hr 50 min GOI,107 kg CO2e,+34% emissions,7394,economy,BOM,CJB
76,8:05 AM,2:10 PM,IndiGo,6 hr 5 min,BOM–CJB,1 stop,3 hr 15 min BLR,103 kg CO2e,+29% emissions,7538,economy,BOM,CJB
77,3:15 PM,1:25 AM+1,IndiGo,10 hr 10 min,CJB–BOM,1 stop,7 hr GOI,107 kg CO2e,+27% emissions,6130,economy,CJB,BOM
78,3:15 PM,7:55 PM,IndiGo,4 hr 40 min,CJB–BOM,1 stop,1 hr 35 min GOI,115 kg CO2e,+37% emissions,7022,economy,CJB,BOM
79,8:30 AM,1:20 PM,IndiGo,4 hr 50 min,CJB–BOM,1 stop,2 hr BLR,106 kg CO2e,+26% emissions,7073,economy,CJB,BOM
80,2:40 PM,7:05 PM,IndiGo,4 hr 25 min,CJB–BOM,1 stop,1 hr 35 min BLR,106 kg CO2e,+26% emissions,7073,economy,CJB,BOM
81,9:25 PM,7:15 AM+1,IndiGo,9 hr 50 min,CJB–BOM,1 stop,6 hr 50 min BLR,104 kg CO2e,+24% emissions,7073,economy,CJB,BOM
82,6:40 PM,10:45 PM,IndiGo,4 hr 5 min,BOM–JAI,1 stop,1 hr 5 min AMD,97 kg CO2e,+15% emissions,6491,economy,BOM,JAI
83,8:50 AM,5:30 PM,IndiGo,8 hr 40 min,BOM–JAI,1 stop,5 hr 25 min AMD,101 kg CO2e,+20% emissions,6491,economy,BOM,JAI
84,1:30 AM,8:00 AM,IndiGo,6 hr 30 min,BOM–JAI,1 stop,3 hr 30 min AMD,101 kg CO2e,+20% emissions,7937,economy,BOM,JAI
85,4:50 PM,9:15 PM,IndiGo,4 hr 25 min,BOM–JAI,1 stop,1 hr 40 min IDR,98 kg CO2e,+17% emissions,9890,economy,BOM,JAI
86,3:45 PM,7:15 PM,IndiGo,3 hr 30 min,BOM–JAI,1 stop,1 hr UDR,106 kg CO2e,+26% emissions,10499,economy,BOM,JAI
87,5:10 AM,2:10 AM+1,Etihad,21 hr,BOM–JAI,1 stop,14 hr 25 min AUH,330 kg CO2e,+293% emissions,48388,economy,BOM,JAI
88,5:05 PM,9:20 PM,IndiGo,4 hr 15 min,JAI–BOM,1 stop,1 hr 50 min UDR,109 kg CO2e,+28% emissions,7551,economy,JAI,BOM
89,6:10 PM,10:05 PM,IndiGo,3 hr 55 min,JAI–BOM,1 stop,1 hr 5 min IDR,101 kg CO2e,+19% emissions,7551,economy,JAI,BOM
90,3:55 AM,7:55 PM,"Etihad, Akasa Air",16 hr,JAI–BOM,1 stop,8 hr 50 min AUH,334 kg CO2e,+293% emissions,50491,economy,JAI,BOM
91,4:30 AM,11:50 AM,IndiGo,7 hr 20 min,BOM–TRV,1 stop,4 hr 5 min BLR,121 kg CO2e,-18% emissions,8961,economy,BOM,TRV
92,6:30 AM,11:50 AM,IndiGo,5 hr 20 min,BOM–TRV,1 stop,2 hr 5 min BLR,121 kg CO2e,-18% emissions,9697,economy,BOM,TRV
93,5:35 AM,10:50 AM,IndiGo,5 hr 15 min,BOM–TRV,1 stop,2 hr 25 min COK,108 kg CO2e,-27% emissions,11393,economy,BOM,TRV
94,8:40 PM,9:10 AM+2,SriLankan,36 hr 30 min,BOM–TRV,1 stop,33 hr CMB,209 kg CO2e,+42% emissions,27472,economy,BOM,TRV
95,8:40 PM,9:10 AM+1,SriLankan,12 hr 30 min,BOM–TRV,1 stop,9 hr CMB,212 kg CO2e,+44% emissions,39833,economy,BOM,TRV
96,4:55 PM,2:50 AM+1,Etihad,9 hr 55 min,BOM–TRV,1 stop,2 hr 25 min AUH,443 kg CO2e,+201% emissions,40439,economy,BOM,TRV
97,11:20 AM,8:15 PM,Etihad,8 hr 55 min,BOM–TRV,1 stop,1 hr 25 min AUH,440 kg CO2e,+199% emissions,55575,economy,BOM,TRV
98,12:20 PM,7:05 PM,IndiGo,6 hr 45 min,TRV–BOM,1 stop,3 hr 40 min BLR,122 kg CO2e,+26% emissions,19092,economy,TRV,BOM
99,9:50 PM,2:05 AM+2,Etihad,28 hr 15 min,TRV–BOM,1 stop,20 hr 50 min AUH,433 kg CO2e,+346% emissions,38747,economy,TRV,BOM
100,9:50 PM,7:00 PM+1,Etihad,21 hr 10 min,TRV–BOM,1 stop,13 hr 50 min AUH,397 kg CO2e,+309% emissions,40755,economy,TRV,BOM
101,9:50 PM,12:40 PM+1,Etihad,14 hr 50 min,TRV–BOM,1 stop,7 hr 25 min AUH,443 kg CO2e,+357% emissions,48023,economy,TRV,BOM
102,9:50 PM,7:10 AM+1,Etihad,9 hr 20 min,TRV–BOM,1 stop,1 hr 55 min AUH,443 kg CO2e,+357% emissions,54245,economy,TRV,BOM
103,10:10 PM,8:55 PM+1,Gulf Air,22 hr 45 min,TRV–BOM,1 stop,14 hr BAH,520 kg CO2e,+436% emissions,65658,economy,TRV,BOM
104,4:15 AM,12:40 PM,Etihad,8 hr 25 min,TRV–BOM,1 stop,55 min AUH,435 kg CO2e,+348% emissions,67540,economy,TRV,BOM
105,5:45 AM,11:10 AM,IndiGo,5 hr 25 min,BOM–IXR,1 stop,1 hr 55 min HYD,140 kg CO2e,+43% emissions,6536,economy,BOM,IXR
106,4:45 PM,9:00 AM+1,Air India Express,16 hr 15 min,BOM–IXR,1 stop,12 hr DEL,212 kg CO2e,+116% emissions,11652,economy,BOM,IXR
107,7:50 PM,12:30 AM+1,IndiGo,4 hr 40 min,IXR–BOM,1 stop,1 hr 10 min AMD,171 kg CO2e,+74% emissions,7194,economy,IXR,BOM
108,2:55 PM,1:50 AM+1,Air India Express,10 hr 55 min,IXR–BOM,1 stop,6 hr 20 min DEL,198 kg CO2e,+102% emissions,13784,economy,IXR,BOM
109,2:55 PM,8:10 PM,Air India Express,5 hr 15 min,IXR–BOM,1 stop,45 min DEL,211 kg CO2e,+115% emissions,14108,economy,IXR,BOM
110,2:45 AM,7:45 AM,IndiGo,5 hr,BOM–PAT,1 stop,1 hr 25 min HYD,151 kg CO2e,+36% emissions,7198,economy,BOM,PAT
111,2:55 PM,8:35 PM,IndiGo,5 hr 40 min,BOM–PAT,1 stop,2 hr 10 min AMD,150 kg CO2e,+35% emissions,7066,economy,BOM,PAT
112,8:00 AM,3:15 PM,IndiGo,7 hr 15 min,BOM–PAT,1 stop,3 hr 20 min DEL,163 kg CO2e,+47% emissions,7198,economy,BOM,PAT
113,1:00 PM,6:00 PM,IndiGo,5 hr,BOM–PAT,1 stop,1 hr 5 min DEL,176 kg CO2e,+59% emissions,7198,economy,BOM,PAT
114,3:00 PM,8:20 PM,IndiGo,5 hr 20 min,BOM–PAT,1 stop,1 hr 30 min DEL,176 kg CO2e,+59% emissions,7198,economy,BOM,PAT
115,3:15 PM,9:00 PM,IndiGo,5 hr 45 min,BOM–PAT,1 stop,2 hr 20 min HYD,151 kg CO2e,+36% emissions,7198,economy,BOM,PAT
116,11:00 PM,7:45 AM+1,IndiGo,8 hr 45 min,BOM–PAT,1 stop,5 hr 10 min HYD,151 kg CO2e,+36% emissions,7198,economy,BOM,PAT
117,3:40 PM,8:30 PM,IndiGo,4 hr 50 min,PAT–BOM,1 stop,1 hr 5 min HYD,156 kg CO2e,+41% emissions,8556,economy,PAT,BOM
118,8:30 AM,2:25 PM,IndiGo,5 hr 55 min,PAT–BOM,1 stop,2 hr 15 min HYD,156 kg CO2e,+41% emissions,8556,economy,PAT,BOM
119,3:50 PM,11:00 PM,IndiGo,7 hr 10 min,PAT–BOM,1 stop,3 hr 5 min DEL,161 kg CO2e,+45% emissions,8556,economy,PAT,BOM
120,6:05 PM,1:00 AM+1,IndiGo,6 hr 55 min,PAT–BOM,1 stop,3 hr 25 min HYD,156 kg CO2e,+41% emissions,8556,economy,PAT,BOM
121,10:10 PM,8:20 AM+1,IndiGo,10 hr 10 min,PAT–BOM,1 stop,6 hr 20 min DEL,161 kg CO2e,+45% emissions,8556,economy,PAT,BOM
122,10:15 AM,2:05 PM,IndiGo,3 hr 50 min,BOM–GOX,1 stop,1 hr 15 min HYD,112 kg CO2e,+143% emissions,4404,economy,BOM,GOX
123,10:15 PM,2:15 AM+2,"IndiGo, Qatar Airways",28 hr,BOM–GOX,1 stop,20 hr 40 min DOH,417 kg CO2e,+807% emissions,82092,economy,BOM,GOX
124,11:00 AM,3:55 PM,IndiGo,4 hr 55 min,GOX–BOM,1 stop,2 hr HYD,114 kg CO2e,+148% emissions,5312,economy,GOX,BOM
125,1:40 PM,6:50 PM,IndiGo,5 hr 10 min,GOX–BOM,1 stop,2 hr 15 min HYD,109 kg CO2e,+137% emissions,5312,economy,GOX,BOM
126,3:15 PM,7:35 PM,IndiGo,4 hr 20 min,BOM–GOI,1 stop,1 hr 35 min HYD,109 kg CO2e,+137% emissions,3944,economy,BOM,GOI
127,11:20 PM,1:10 AM+1,Akasa Air,1 hr 50 min,BOM–BLR,Nonstop,0 minutes,73 kg CO2e,+6% emissions,4881,economy,BOM,BLR
128,8:05 AM,9:55 AM,IndiGo,1 hr 50 min,BOM–BLR,Nonstop,0 minutes,69 kg CO2e,Avg emissions,5716,economy,BOM,BLR
129,1:10 AM,3:05 AM,IndiGo,1 hr 55 min,BOM–BLR,Nonstop,0 minutes,71 kg CO2e,Avg emissions,5716,economy,BOM,BLR
130,6:30 AM,8:25 AM,IndiGo,1 hr 55 min,BOM–BLR,Nonstop,0 minutes,71 kg CO2e,Avg emissions,5716,economy,BOM,BLR
131,9:50 AM,11:55 AM,IndiGo,2 hr 5 min,BOM–BLR,Nonstop,0 minutes,71 kg CO2e,Avg emissions,5716,economy,BOM,BLR
132,12:30 PM,2:25 PM,IndiGo,1 hr 55 min,BOM–BLR,Nonstop,0 minutes,71 kg CO2e,Avg emissions,5716,economy,BOM,BLR
133,2:30 PM,4:25 PM,IndiGo,1 hr 55 min,BOM–BLR,Nonstop,0 minutes,71 kg CO2e,Avg emissions,5716,economy,BOM,BLR
134,3:35 PM,5:25 PM,IndiGo,1 hr 50 min,BOM–BLR,Nonstop,0 minutes,71 kg CO2e,Avg emissions,5716,economy,BOM,BLR
135,5:00 PM,6:55 PM,IndiGo,1 hr 55 min,BOM–BLR,Nonstop,0 minutes,71 kg CO2e,Avg emissions,5716,economy,BOM,BLR
136,6:30 PM,8:25 PM,IndiGo,1 hr 55 min,BOM–BLR,Nonstop,0 minutes,71 kg CO2e,Avg emissions,5716,economy,BOM,BLR
137,7:50 PM,9:45 PM,IndiGo,1 hr 55 min,BOM–BLR,Nonstop,0 minutes,71 kg CO2e,Avg emissions,5716,economy,BOM,BLR
138,9:30 PM,11:25 PM,IndiGo,1 hr 55 min,BOM–BLR,Nonstop,0 minutes,71 kg CO2e,Avg emissions,5716,economy,BOM,BLR
139,10:20 PM,12:20 AM+1,IndiGo,2 hr,BOM–BLR,Nonstop,0 minutes,71 kg CO2e,Avg emissions,5716,economy,BOM,BLR
140,8:05 PM,9:45 PM,Akasa Air,1 hr 40 min,BOM–BLR,Nonstop,0 minutes,69 kg CO2e,Avg emissions,5875,economy,BOM,BLR
141,7:50 PM,9:50 PM,SpiceJet,2 hr,BOM–BLR,Nonstop,0 minutes,83 kg CO2e,+20% emissions,5916,economy,BOM,BLR
142,10:30 PM,12:30 AM+1,SpiceJet,2 hr,BOM–BLR,Nonstop,0 minutes,83 kg CO2e,+20% emissions,5916,economy,BOM,BLR
143,2:05 AM,4:10 AM,Air India,2 hr 5 min,BOM–BLR,Nonstop,0 minutes,82 kg CO2e,+19% emissions,5971,economy,BOM,BLR
144,6:35 AM,8:35 AM,Air India,2 hr,BOM–BLR,Nonstop,0 minutes,82 kg CO2e,+19% emissions,5971,economy,BOM,BLR
145,7:55 AM,10:05 AM,Air India,2 hr 10 min,BOM–BLR,Nonstop,0 minutes,82 kg CO2e,+19% emissions,6071,economy,BOM,BLR
146,10:00 AM,12:05 PM,Air India,2 hr 5 min,BOM–BLR,Nonstop,0 minutes,82 kg CO2e,+19% emissions,6071,economy,BOM,BLR
147,12:00 PM,2:05 PM,Air India,2 hr 5 min,BOM–BLR,Nonstop,0 minutes,82 kg CO2e,+19% emissions,6071,economy,BOM,BLR
148,3:25 PM,5:35 PM,Air India,2 hr 10 min,BOM–BLR,Nonstop,0 minutes,82 kg CO2e,+19% emissions,6071,economy,BOM,BLR
149,8:45 PM,10:45 PM,Air India,2 hr,BOM–BLR,Nonstop,0 minutes,82 kg CO2e,+19% emissions,6071,economy,BOM,BLR
150,11:00 AM,12:55 PM,IndiGo,1 hr 55 min,BOM–BLR,Nonstop,0 minutes,71 kg CO2e,Avg emissions,6103,economy,BOM,BLR
151,8:45 AM,10:40 AM,Akasa Air,1 hr 55 min,BOM–BLR,Nonstop,0 minutes,72 kg CO2e,Avg emissions,6339,economy,BOM,BLR
152,9:45 PM,11:45 PM,Akasa Air,2 hr,BOM–BLR,Nonstop,0 minutes,70 kg CO2e,Avg emissions,6339,economy,BOM,BLR
153,6:30 PM,8:35 PM,Air India,2 hr 5 min,BOM–BLR,Nonstop,0 minutes,82 kg CO2e,+19% emissions,6669,economy,BOM,BLR
154,7:30 AM,9:25 AM,Akasa Air,1 hr 55 min,BLR–BOM,Nonstop,0 minutes,72 kg CO2e,Avg emissions,5783,economy,BLR,BOM
155,6:00 AM,7:55 AM,Akasa Air,1 hr 55 min,BLR–BOM,Nonstop,0 minutes,72 kg CO2e,Avg emissions,5982,economy,BLR,BOM
156,4:00 PM,5:45 PM,IndiGo,1 hr 45 min,BLR–BOM,Nonstop,0 minutes,70 kg CO2e,Avg emissions,6320,economy,BLR,BOM
157,7:05 PM,8:40 PM,IndiGo,1 hr 35 min,BLR–BOM,Nonstop,0 minutes,70 kg CO2e,Avg emissions,6320,economy,BLR,BOM
158,1:00 AM,2:50 AM,IndiGo,1 hr 50 min,BLR–BOM,Nonstop,0 minutes,70 kg CO2e,Avg emissions,6320,economy,BLR,BOM
159,3:45 AM,5:30 AM,IndiGo,1 hr 45 min,BLR–BOM,Nonstop,0 minutes,70 kg CO2e,Avg emissions,6320,economy,BLR,BOM
160,5:30 AM,7:15 AM,IndiGo,1 hr 45 min,BLR–BOM,Nonstop,0 minutes,68 kg CO2e,Avg emissions,6320,economy,BLR,BOM
161,7:25 AM,9:10 AM,IndiGo,1 hr 45 min,BLR–BOM,Nonstop,0 minutes,70 kg CO2e,Avg emissions,6320,economy,BLR,BOM
162,8:30 AM,10:15 AM,IndiGo,1 hr 45 min,BLR–BOM,Nonstop,0 minutes,70 kg CO2e,Avg emissions,6320,economy,BLR,BOM
163,10:15 AM,12:05 PM,IndiGo,1 hr 50 min,BLR–BOM,Nonstop,0 minutes,70 kg CO2e,Avg emissions,6320,economy,BLR,BOM
164,11:30 AM,1:20 PM,IndiGo,1 hr 50 min,BLR–BOM,Nonstop,0 minutes,70 kg CO2e,Avg emissions,6320,economy,BLR,BOM
165,1:00 PM,2:50 PM,IndiGo,1 hr 50 min,BLR–BOM,Nonstop,0 minutes,70 kg CO2e,Avg emissions,6320,economy,BLR,BOM
166,2:20 PM,4:05 PM,IndiGo,1 hr 45 min,BLR–BOM,Nonstop,0 minutes,70 kg CO2e,Avg emissions,6320,economy,BLR,BOM
167,5:15 PM,7:05 PM,IndiGo,1 hr 50 min,BLR–BOM,Nonstop,0 minutes,70 kg CO2e,Avg emissions,6320,economy,BLR,BOM
168,8:15 PM,10:00 PM,IndiGo,1 hr 45 min,BLR–BOM,Nonstop,0 minutes,70 kg CO2e,Avg emissions,6320,economy,BLR,BOM
169,10:20 PM,12:05 AM+1,IndiGo,1 hr 45 min,BLR–BOM,Nonstop,0 minutes,70 kg CO2e,Avg emissions,6320,economy,BLR,BOM
170,4:15 AM,6:15 AM,SpiceJet,2 hr,BLR–BOM,Nonstop,0 minutes,83 kg CO2e,+20% emissions,6414,economy,BLR,BOM

#### Number of flights:

In [20]:
len(df_bom)

462

#### Average price:

In [38]:

print(df_bom["Price"].mean())

8451.89393939394

#### Number of flights to (and fro) each destination:

In [39]:
# Flights from BOM 
from_bom = (
    df_bom[df_bom["Source"] == "BOM"]
    .groupby("Destination")
    .size()
    .rename("Flights from BOM")
)

# Flights to BOM 
to_bom = (
    df_bom[df_bom["Destination"] == "BOM"]
    .groupby("Source")
    .size()
    .rename("Flights to BOM")
)

# Combine 
flights_bom = pd.concat([to_bom, from_bom], axis=1).fillna(0).astype(int)

flights_bom.index.name = "Airport"
flights_bom = flights_bom.reset_index()

print(flights_bom)

   Airport  Flights to BOM  Flights from BOM
0      BLR              28                32
1      CCU              15                22
2      CJB               8                 6
3      COK              14                10
4      DEL              59                58
5      GOI               9                10
6      GOX               6                 6
7      HYD              24                21
8      IXC               9                 7
9      IXE               6                 8
10     IXG               1                 1
11     IXR               5                 4
12     JAI               6                 9
13     MAA              20                20
14     PAT               9                11
15     TRV               9                 9